CREATE TABLE IF NOT EXISTS USERS(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    STD_ID INTEGER NOT NULL UNIQUE,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    VERIFIED VARCHAR(5) DEFAULT 'NO'
);

CREATE TABLE IF NOT EXISTS POLL(
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(50) NOT NULL,
    STARTED_AT TIMESTAMPTZ NOT NULL,
    FINISHED_AT TIMESTAMPTZ NOT NULL,
    VISIBILITY VARCHAR(10) DEFAULT 'PUBLIC',
    RESULT_VISIBILITY VARCHAR(10) DEFAULT 'PUBLIC',
    MIN_SELECT INTEGER NOT NULL,
    MAX_SELECT INTEGER NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS GROUPS(
    ID SERIAL PRIMARY KEY,
    POLL_ID INTEGER NOT NULL,
    MIN_STDID INTEGER NOT NULL,
    MAX_STDID INTEGER NOT NULL,
    POINT INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS MODERATIONS(
    POLL_ID INTEGER,
    STD_ID INTEGER,
    ROLE VARCHAR(10) DEFAULT 'MODERATOR',
    PRIMARY KEY (POLL_ID,STD_ID)
);

CREATE TABLE IF NOT EXISTS SUBPOLL(
    POLL_ID INTEGER,
    SUBPOLL_ID INTEGER,
    PRIMARY KEY (POLL_ID, SUBPOLL_ID)
);

CREATE TABLE IF NOT EXISTS VOTED(
    STD_ID INTEGER,
    POLL_ID INTEGER,
    VOTED_AT TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (STD_ID, POLL_ID)
);


CREATE TABLE IF NOT EXISTS OPTIONS(
    ID SERIAL PRIMARY KEY,
    POLL_ID INTEGER,
    TEXT VARCHAR(100),
    SCORE INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS OTP(
    ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(50),
    OTP_CODE VARCHAR(8),
    SENT_AT TIMESTAMPTZ DEFAULT NOW()

)
