CREATE TABLE IF NOT EXISTS USERS(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    STD_ID INTEGER NOT NULL UNIQUE,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    VERIFIED VARCHAR(5) DEFAULT 'NO'
);

CREATE TABLE IF NOT EXISTS POLL(
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(50) NOT NULL,
    STARTED_AT DATE NOT NULL,
    FINISHED_AT DATE NOT NULL,
    VISIBILITY VARCHAR(10) DEFAULT 'PUBLIC',
    RESULT_VISIBILITY VARCHAR(10) DEFAULT 'PUBLIC',
    MIN_SELECT INTEGER NOT NULL,
    MAX_SELECT INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS GROUPS(
    ID SERIAL PRIMARY KEY,
    POLL_ID INTEGER NOT NULL,
    POINT INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS MODERATIONS(
    POLL_ID INTEGER,
    STD_ID INTEGER,
    ROLE VARCHAR(10) DEFAULT 'MODERATOR'
);

CREATE TABLE IF NOT EXISTS SUBPOLL(
    POLL_ID INTEGER,
    SUBPOLL_ID INTEGER
);

CREATE TABLE IF NOT EXISTS VOTED(
    STD_ID INTEGER,
    POLL_ID INTEGER,
    VOTED_AT TIMESTAMP DEFAULT NOW()
);

